apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: strapi-pipeline-stage
spec:
  resources:
    - name: strapi-repo-stage
      type: git
    - name: strapi-image-stage
      type: image

  params:
    - name: APP_NAME
      description: The name of the application
      default: 'strapi'      
    - name: APP_VERSION
      description: The version of the application
      default: '1.0.0'      
    - name: DEPLOY_PROJECT
      description: The project where you deploy the app
      default: 'stage-env'

  tasks:
  - name: build
    taskRef:
      name: build-strapi-app
    resources:       
      inputs:
        - name: source
          resource: strapi-repo-stage
      outputs:
        - name: image
          resource: strapi-image-stage

  - name: deploy
    taskRef:
      name: deploy-strapi-app-stage
    runAfter:
      - build
    params:
        - name: APP_NAME
          value: "$(params.APP_NAME)"
        - name: APP_VERSION
          value: "$(params.APP_VERSION)"  
        - name: DEPLOY_PROJECT
          value: "$(params.DEPLOY_PROJECT)"    
    resources:
      inputs:
        - name: image
          resource: strapi-image-stage

  - name: test
    taskRef:
      name: test-strapi-app
    runAfter:
      - deploy
    params:
      - name: APP_NAME
        value: "$(params.APP_NAME)"
      - name: APP_VERSION
        value: "$(params.APP_VERSION)"
      - name: DEPLOY_PROJECT
        value: "$(params.DEPLOY_PROJECT)"

  - name: promote
    taskRef:
      name: promote-strapi-to-prod-cluster
    runAfter:
      - test
    params:
      - name: APP_NAME
        value: "$(params.APP_NAME)"
      - name: APP_VERSION
        value: "$(params.APP_VERSION)"
      - name: STAGE_PROJECT
        value: "$(params.DEPLOY_PROJECT)"
      - name: PROD_PROJECT
        value: "ual-prod-env"