apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-strapi-app
spec:
    params:
      - name: APP_NAME
        description: The name of the application
        default: 'strapi'
        type: string
      - name: APP_VERSION
        description: The version of the application
        default: '1.0.0'
        type: string
      - name: DEPLOY_PROJECT
        description: The project where you deploy the app
        default: 'stage-env'
        type: string  

    steps:
      - name: test-app
        image: quay.io/openshift/origin-cli:4.3.0
        workingDir: /workspace/source
        command: ["/bin/bash", "-c"]
        args:
          - |-
            oc get dc $(inputs.params.APP_NAME) -n $(inputs.params.DEPLOY_PROJECT)